# Generated by Django 2.2.6 on 2019-11-07 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangoproject', '0012_auto_20191107_1140'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='institute',
            field=models.IntegerField(choices=[(1, 'University of Central Punjab  '), (2, 'Lahore Medical And Dental College')], default=1, max_length=50),
        ),
    ]
