# Generated by Django 2.2.6 on 2019-11-07 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangoproject', '0014_auto_20191107_1159'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='institute',
            field=models.CharField(choices=[('UCP', 'University of Central Punjab  '), ('LMDC', 'Lahore Medical And Dental College')], default='UCP', max_length=50),
        ),
    ]
