# Generated by Django 2.2.6 on 2019-11-07 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangoproject', '0015_auto_20191107_1200'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='institute',
            field=models.CharField(choices=[('University of Central Punjab  ', 'University of Central Punjab  '), ('Lahore Medical And Dental College', 'Lahore Medical And Dental College')], default='University of Central Punjab  ', max_length=50),
        ),
    ]
